### ISSUE TITLE
WinXAudio2 problem.

### ISSUE THREAD

**Issue by Achaean** [aperture-software/colditz-escape#1]
Hi! :-)
Well...the usual message:

Audio Initialization Failure

Audio could not be initialized (WinXAudio2).
Please make sure you have a recent version of DirectX installed.

ΟΚ   

I read the solution on FAQ, but I'm on Win 10 x64.
Latest DX version!
G.

**Comment by aperture-software** [comment]
I'm not seeing any issue on Windows 10 x64, and, according to [Microsoft' documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.xaudio2.xaudio2create(v=vs.85).aspx), XAudio 2 should be fully supported on Windows 10 as well.

Since I cannot replicate the issue, I will close it.
