### ISSUE TITLE
polish flag

### ISSUE THREAD

**Issue by Peceha** [aperture-software/colditz-escape#12]
hello,
please rotate the flag 90deg clockwise
at the moment only colors are ok, orientation is wrong

**Comment by aperture-software** [comment]
This engine is a recreation of the original Amiga game and uses the original image bitmaps found in the game data.

While I acknowledge that the Polish Flag should have been rotated by the original developers, to be consistent with the orientation of the other flags, I'm afraid that, since this is not really a game breaker, I am not planning to edit the game data or apply a patch to the engine do so.
